export const SDG = [
  {
    id: "1",
    name: "SDG 1",
    label: "No Poverty",
    color: "#E5243B",
  },
  {
    id: "2",
    name: "SDG 2",
    label: "Zero Hunger",
    color: "#DDA63A",
  },
  {
    id: "3",
    name: "SDG 3",
    label: "Good Health and Well-being",
    color: "#4C9F38",
  },
  {
    id: "4",
    name: "SDG 4",
    label: "Quality Education",
    color: "#C5192D",
  },
  {
    id: "5",
    name: "SDG 5",
    label: "Gender Equality",
    color: "#FF3A21",
  },
  {
    id: "6",
    name: "SDG 6",
    label: "Clean Water and Sanitation",
    color: "#26BDE2",
  },
  {
    id: "7",
    name: "SDG 7",
    label: "Affordable and Clean Energy",
    color: "#FCC30B",
  },
  {
    id: "8",
    name: "SDG 8",
    label: "Decent Work and Economic Growth",
    color: "#A21942",
  },
  {
    id: "9",
    name: "SDG 9",
    label: "Industry, Innovation and Infrastructure",
    color: "#FD6925",
  },
  {
    id: "10",
    name: "SDG 10",
    label: "Reduced Inequality",
    color: "#DD1367",
  },
  {
    id: "11",
    name: "SDG 11",
    label: "Sustainable Cities and Communities",
    color: "#FD9D24",
  },
  {
    id: "12",
    name: "SDG 12",
    label: "Responsible Consumption and Production",
    color: "#BF8B2E",
  },
  {
    id: "13",
    name: "SDG 13",
    label: "Climate Action",
    color: "#3F7E44",
  },
  {
    id: "14",
    name: "SDG 14",
    label: "Life Below Water",
    color: "#0A97D9",
  },
  {
    id: "15",
    name: "SDG 15",
    label: "Life on Land",
    color: "#56C02B",
  },
  {
    id: "16",
    name: "SDG 16",
    label: "Peace and Justice Strong Institutions",
    color: "#00689D",
  },
  {
    id: "17",
    name: "SDG 17",
    label: "Partnerships to achieve the Goal",
    color: "#19486A",
  },
];
